### ISSUE TITLE
latest build for 1.20.1 is not compatible with neoforge 1.20.1

### ISSUE THREAD

**Issue by baeZipster** [MrCrayfish/Framework#16]
it says it requires 47.2.0 but neoforge's latest is 47.1.99
if this is just a versioning oversight, and the mod itself can work on neoforge, id change the versioning requirements to allow neoforge's 1.20.1 versions

**Comment by jamieb999** [comment]
I reported the same error on February 14 2024 and the developer of this mod just
closed it off and refused to do anything telling me to run Forge not NeoForge and then
proceeded to close off the ticket. 

See https://github.com/MrCrayfish/Framework/issues/15

"Framework is not supported and won't be available for NeoForge on 
Minecraft 1.20.1 regardless of the compatibility (non-guaranteed) that NeoForge advertised. "

The dev refuses to support NeoForge on 1.20.1 and I asked them to change the version 
numbering to support Neoforged and the developer won't do it. 

One of the things I hate about Minecraft Java is when you get developers
like this that don't know what they are doing and refuses to 
support a current version that most people use. 

No one is running Forge any more it is dead and I told the developer that
and the developer refuses to do anything to fix this issue.  I am about to
uninstall any mod made by this person because the dev is just a jerk. 

I would suggest everyone else do the same as well don't run mods made
by this dev!

**Comment by Enderteck** [comment]
> I reported the same error on February 14 2024 and the developer of this mod just closed it off and refused to do anything telling me to run Forge not NeoForge and then proceeded to close off the ticket.
> 
> See #15
> 
> "Framework is not supported and won't be available for NeoForge on Minecraft 1.20.1 regardless of the compatibility (non-guaranteed) that NeoForge advertised. "
> 
> The dev refuses to support NeoForge on 1.20.1 and I asked them to change the version numbering to support Neoforged and the developer won't do it.
> 
> One of the things I hate about Minecraft Java is when you get developers like this that don't know what they are doing and refuses to support a current version that most people use.
> 
> No one is running Forge any more it is dead and I told the developer that and the developer refuses to do anything to fix this issue. I am about to uninstall any mod made by this person because the dev is just a jerk.
> 
> I would suggest everyone else do the same as well don't run mods made by this dev!

Can't the devs just re-release an older Forge version with the NeoForge tag version to be compatible with the more used NeoForge ? or just change the requirement of the latest Forge version to have lower Neoforge requirements.

Forge is gonna die, whether you like it or not, Supporting the modloader that has a future makes sense even for 1.20.1. It's still a recent version and we don't even have 1.20.5 yet !

Just look and tell me you don't see it:

https://github.com/MinecraftForge/MinecraftForge/pulse
https://github.com/neoforged/NeoForge/pulse

**Comment by Enderteck** [comment]
Anu updates ? I can't still can't update Framework on my modpack...

Does the latest Framework version really require the latest forge version or is it actually compatible with the latest NeoForge release if you edit the mods version requirement ?

**Comment by Enderteck** [comment]
Looks fixed to me. Nice

**Comment by MrCrayfish** [comment]
Should be fixed now. I downgrade to Forge 47.1.47, which should make it compatible with NeoForge on 1.20.1
